### ISSUE TITLE
Race Finish Bug

### ISSUE THREAD

**Issue by Blackyvk** [storm345dev/MarioKart#7]
This bug is persistent since 6.1

When you win a race and others are still racing if someone uses a Lightning you get struck by one or if someone uses the Ghost, you get the bone door and egg outside the game plus the dizzy effect, and you still can see the scoreboard on the right, i even tried adding a region on the game exit that executes the command /race leave and didnt work, you have to wait for everyone to finish the race. 

I think it should kick you out of the race and restore the inventory as soon as you arrive the finish line.

 I also remember someone saying something about getting struck by lightnings from different races, like if you use lightning in race 1, that lightning also affects race 2, all races are in the same map. i'll confirm this later when I get the opportunity.

**Comment by storm345** [comment]
Indeed if a player finishes a race they aren't 100% removed. The powerups still affecting them is unintentional and I will fix it when I have time :)
